config/routes.rb
Rails.application.routes.draw do
  resources :users

  # default view pages named routes
  root 'default_view_pages#home'
  get '/tutorial', to: 'default_view_pages#tutorial'
  get '/about', to: 'default_view_pages#about'
  get '/contact', to: 'default_view_pages#contact'

  # user (sign up and sign in) named routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # sessions (signup and signout) named routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # user application named routes
  get '/image_differences', to: 'image_differences#index'
  get '/image_differences_generate', to: 'image_differences#show'
end

app/controllers/default_view_pages_controller.rb
class DefaultViewPagesController < ApplicationController
  def home
  end

  def tutorial
  end

  def about
  end

  def contact
  end
end

app/helpers/default_view_pages_helper.rb
module DefaultViewPagesHelper
end

app/views/default_view_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About Page</h1>
<p>This page will provide information about application (similar information found in Github details).</p>

<%= link_to "Home", root_path %>
<%= link_to "Tutorial", tutorial_path %>
<%= link_to "Contact", contact_path %>

app/views/default_view_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact Page</h1>
<p>This page will display all information about myself and my social media information.</p>

<%= link_to "Tutorial", tutorial_path %>
<%= link_to "About", about_path %>
<%= link_to "Home", root_path %>

app/views/default_view_pages/home.html.erb
<% provide(:title, "Home") %>

<%= react_component("UserApplications") %>

<h1>Conceptual Ideas Application (home)</h1>
<p>This page will display all available/independent features of application.</p>

<%= link_to "Tutorial", tutorial_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>


<br/>

app/views/default_view_pages/tutorial.html.erb
<% provide(:title, "Tutorial") %>

<h1>Tutorial Page</h1>
<p>This page will display intuitive information about how to get up and running with application.</p>

<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>